language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - 'nightly'

services:
  - memcached

matrix:
  allow_failures:
    - php: '7.4snapshot'
    - php: 'nightly'

before_script:
  - composer install
  - wget https://github.com/infection/infection/releases/download/0.13.0/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.13.0/infection.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
  - gpg --with-fingerprint --verify infection.phar.asc infection.phar
  - chmod +x infection.phar

script:
  - ./infection.phar --min-msi=48 -j$(nproc)
